### ISSUE TITLE
APP_URL:8080/dev and vue devtools

### ISSUE THREAD

**Issue by abogdan0505** [gianlucacandiotti/laravue#6] opened 2016-11-08 07:06 UTC
I scaffolded this project template, after I ran npm run build and then npm run dev outside homestead went to localhost:8080 ->  I see the Laravue center text and everything seems ok with the exception of three problems.

Problem 1: after running localhost:8080, in the console i have a bunch of errors:
err1: vue.common.js?717d:2643[Vue warn]: Property or method "routeHasLogin" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in anonymous component at /Users/user/web/sites/laravelvue/resources/assets/js/components/Hello.vue)

err2: Uncaught TypeError: Cannot read property 'hasAttribute' of null(…)(anonymous function) @ global-shortcut.js:9(anonymous function) @ global-shortcut.js:21

err3: backend.js:1 Uncaught TypeError: Cannot read property 'appendChild' of null(…) --> This error appears when I hover over the vue component in vue devtools which seems to show as to be : Annonymous

Problem 2:  When i go to:  http://laravelvue.app:8080/dev (I run this project in homestead), I get this text in the dom: Error occured while trying to proxy to: laravelvue.app:8080/   
I also get this when i go to localhost:8080/dev

Problem 3: After running laravelvue.app 8000 (homestead) i get this error in console: GET http://laravelvue.app:8000/app.js 404 (Not Found) and i CAN'T see the Laravue centered text, but if I replace the src='/app.js' with src='http://localhost.8000/app.js' in the script in the views/layouts/base.blade.php i CAN see the Laravue centered text but i have two errors in console:
err1: global-shortcut.js:9 Uncaught TypeError: Cannot read property 'hasAttribute' of null(…)
err2: (index):1 GET http://laravelvue.app:8000/__webpack_hmr (this one autorepeats at a timeinterval in the console) 

Can you please help me get this going? Thanks

**Comment by gianlucacandiotti** [comment] 2016-11-08 15:00
Hello,

Thank you for taking the time to detail all your problems, I just saw the email. Right now I'm at work, but I can help you when I get home around 6 pm (10 am right now) and try to reproduce and explain everything.

Doing a quick read, some things you may try are:

1. Check your **.env** file. In that file I define the port Webpack will use for the development server. The variable is called **APP_DEV_PORT** and by default its value is **8080**. This is only used for development while running the **npm run dev** command. So trying to use other ports like **8000** will be useless unless you changed it there.
2. In that same file I also defined a variable called **APP_URL** that is used by the Webpack Dev Server as the target for the proxy. This is because while in development, in order to use HMR I have to run the application through Webpack, but I also want Laravel to handle the request itself. If the url that maps to your project in your Homestead.yaml is: **laravelvue.app**, in your **.env** file you should have **APP_URL=http://laravelvue.app**.
3. If you run **localhost:8080** without the **dev** at the end, it means you are running the application through the Webpack Dev Server, but not Laravel. That's why you get some errors, because there are variables that get to the view through Laravel and the Vue Component is trying to use them but they don't exist in that scenario.

I'll still check them when I get home, update me with anything else you find or tell me if these things were helpful. Thanks !

**Comment by abogdan0505** [comment] 2016-11-09 09:17
Thank you for your response, it helped me find out something strange:
1. Immediately after making a fresh install of the package with composer and after running npm install I went to .env and changed APP_URL=http://localhost to http://laravue.app. After that I ran npm run build and went to laravue.app:8080 and chrome threw me the 'This site can’t be reached' error but after I changed the port (chrome url) to laravue.app:8000 it took me to the page with centered Laravue title with vue, laravel doc links.. etc without any errors in the chrome inspector console.
2. I went outside homestead and ran npm run dev .. it showed me an error regarding my node version.. but I ran npm rebuild node-sass and fixed it. Then i ran npm run dev again and i got no errors in the terminal but when i went back to chrome http://laravue.app:8000 (which didnt showed me errors before) now shows me in the chrome console (index):30 GET http://laravue.app:8000/app.js.
More specifically this line: <script type="text/javascript" src="/app.js"></script>
But the strangest thing for me is that in the same file (index) from where the error occurs, inside the body we have a <script> window.injectors.baseUrl = 'http://laravue.app:8000:8080/dev'</script> <--- it shows two ports, thats the problem.. 
Now.. how can i fix this?.. i dont know why i got port 8000 or where it comes from.. i followed the steps exactly like in documentation you provided, I also made the settings inside etc/hosts with 127.0.0.1 laravue.app, inside Homestead.yaml i mapped the new project correctly.. i even did a vagrant provision after i made the settings.. And i told u, it worked before running npm run dev outside homestead.. thats the moment when I noticed it broked
I cant figure out where the extra 8000 port comes from and why does it work with port 8000 and not with 8080 since i didn't touch the .env file just at APP_URL=http://laravue.app

**Comment by gianlucacandiotti** [comment] 2016-11-09 11:55
Hi again,

Could you try these steps please. I will assume the same APP_URL using right now.

1. Fresh install.
2. Run **npm install**.
3. Run **npm run build**.
4. Go into your browser and open it like you would open any other Laravel project. In your case it would be **laravue.app**. Don't add the port **8080** because that's the Webpack Dev Server port and it isn't running so it will tell you the page doesn't exist.

Since **npm run build** just generates the assets, Webpack now has nothing to do with how you serve the page. Now it should be just another Laravel application with production ready assets. I don't use port **8000** for my Laravel applications inside homestead, I haven't configured anything, I just map to the public folder inside the project and that's it.

Now for development, in the same project try these steps:

1. Run **npm run dev**.
2. Wait until the console tells you evryhing is ready.
3. Go into your browser and hit **laravue.app:8080/dev**.

Now that the **npm run dev** command is being used, the Webpack Dev Server is working and in order to run the application through webpack you have to use the port **8080** which is the default port for development specified in the **.env** file. The **/dev** section of the url is also necessary to forward the request to the Laravel application (That means it forwards the request to the url you specified in your **.env** file, in your case **http://laravue.app**) and this is only used for development by the Webpack Dev Server.

If you must use port **8000** in order to serve your Laravel applications that may be a problem. But by default you don't have to specify any port. I think I know why that happens. You said you mapped **127.0.0.1** to **laravue.app** inside **etc/hosts**. Can your try changing it to map **192.168.10.10** (the Homestead.yaml default ip listed at the top, if you changed it, use the one you have listed there) to **laravue.app** instead. This is because since you are mapping your host's machine localhost to the application's url, when you hit in your browser **laravue.app**, it goes to your localhost first, then you add port **8000** and homestead by default forwards port **8000** in your host machine to port **80** in the virtual machine. Please just try changing that in your **etc/hosts** file to use the homestead's ip instead, that way you don't have to specify the port in the url anymore, and it won't create a conflict when trying to use the Webpack Dev Server port and your local machine's port at the same time.

That should do it. Tell me if you get it to work. Thanks !

**Comment by gianlucacandiotti** [comment] 2016-11-09 12:06
Please read the last part of my last comment before trying the steps I listed since it gives more insight about your current setup and how to stop using port **8000** to serve you Laravel applications inside Homestead.

If you try the steps first, after building you will have to go to **laravue.app:8000** to see the application.

**Comment by abogdan0505** [comment] 2016-11-10 07:19
Thank you again for your time on this. 
Unfortunately I didn't manage to make it work. No doubt the problem is my settings but I cant seem to wrap my head around what is going on.
I did a fresh install (changed to 192.168.10.10, now i cant access it like you sayd), ran npm install, build then after i go to http://laravue.app i can see the project just fine.
After npm run build: -> http://laravue.app
<img width="1271" alt="screen shot 2016-11-10 at 08 43 33" src="https://cloud.githubusercontent.com/assets/17160658/20167703/d8dd7f56-a725-11e6-84eb-0559cdc20a47.png">
After npm run dev: -> http://laravue.app:8080/dev
![screen shot 2016-11-10 at 09 16 53](https://cloud.githubusercontent.com/assets/17160658/20167783/7984fb5a-a726-11e6-8ad6-90a3300266a0.png)
Then back to http://laravue.app
<img width="1277" alt="screen shot 2016-11-10 at 08 46 26" src="https://cloud.githubusercontent.com/assets/17160658/20167802/a5f57e26-a726-11e6-9e92-dd9e5fb4f5c5.png">
Also this: http://laravue.app:8080
<img width="1279" alt="screen shot 2016-11-10 at 08 52 37" src="https://cloud.githubusercontent.com/assets/17160658/20167815/bb7d3cde-a726-11e6-97a3-28e5db549beb.png">

**Comment by abogdan0505** [comment] 2016-11-10 07:46
Yep. It works now. Thank you again for your time on this.

**Comment by gianlucacandiotti** [comment] 2016-11-10 14:20
Hi again!

From the steps you mention, the commands themselves are ok, but why are you running the npm commands from your host machine ? Go into homestead and from there run the npm commands. When you run **npm run dev** from you host machine, it will start the process from there and open port **8080** for your localhost but it won't work from within homestead. Since you are now mapping **192.168.10.10** to **newlaravue.app**, now that url points to the homestead's localhost basically, which doesn't have port **8080** open since you started the Webpack Dev Server from your localhost.

I hope this time it works! Basically just go into homestead and run **npm run dev** from there. I recommend doing everything from there so you don't have any conflict because of the different versions of node and npm you may have installed in your host machine and homestead. Update your homestead repository and homestead vagrant box if the versions are not up to date.

Tell me if it works. Thanks!

**Comment by abogdan0505** [comment] 2016-11-11 11:10
Yep. It works now. Thank you for your time on this.
I still need to run the npm run dev command from both my host machine and from homestead but it works.
Now, because im not so familiar with laravel, blade.. and all that stuff.. after I made the users migration i have the app.blade.php in the layouts folder, if i go to login or register i cant see the styles or js because they aren't loaded... I get the layout elements but i dont get the app.js or app.css.

**Comment by gianlucacandiotti** [comment] 2016-11-11 12:37
Hey! I'm glad that we got the first thing worked out. I'm not sure why you got to run the command from both your host machine and homestead, you will just run the process from both environments and seems a bit unnecessary. But if that works for you I'm closing this issue.

If you want to discuss another topic like the Auth pages generated by Laravel you can open another issue to keep the threads focused on one thing. I'll still respond about it here as the last comment.

I haven't done anything yet about the Auth pages or any page that Laravel could generate for you. The project is fairly new and I was just contemplating using the project as an API Client. You can manually adapt the Login or Sign Up pages so that they extend the base layout, although I haven't really checked how that would look like considering the styles or other stuff Laravel provides for those pages. Also probably the links or actions from those pages to the router are probably using the Laravel's helpers, and you have to switch those to the custom route helpers I created in order to manage the redirections to go to the Webpack Dev Server.

With some time I'll cover those use cases, I'm just really busy right now and only modified what I needed.  I'm accepting pull requests if the code is well made and cover general things like the ones you mention. For the time being you can manually change them, it won't be that hard.

I apologize for the inconvenience.

**Closed by gianlucacandiotti** 2016-11-11 12:37 UTC
Labels: help wanted
